# Generated by Django 4.1.7 on 2023-04-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0004_order_product_digital_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
