# Generated by Django 4.1.7 on 2023-04-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0005_remove_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
