# Generated by Django 4.1.7 on 2023-04-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0010_shippingaddress_expedition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='expedition',
        ),
        migrations.AddField(
            model_name='order',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchandise_web.expedition'),
        ),
    ]
