# Generated by Django 4.1.7 on 2023-04-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0011_remove_shippingaddress_expedition_order_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=200, null=True)),
                ('payment_number', models.CharField(max_length=200, null=True)),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='images/payment/')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchandise_web.payment'),
        ),
    ]
