# Generated by Django 4.1.7 on 2023-04-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0012_payment_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_number',
            new_name='number',
        ),
    ]
