# Generated by Django 4.1.7 on 2023-04-23 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandise_web', '0013_rename_payment_image_payment_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Shipment',
        ),
    ]
