# Generated by Django 4.1.7 on 2023-04-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0014_rename_shippingaddress_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='order_id',
        ),
    ]
