# Generated by Django 4.1.7 on 2023-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0015_rename_transaction_id_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
