# Generated by Django 4.1.7 on 2023-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0016_expedition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
