# Generated by Django 4.1.7 on 2023-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0021_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
