# Generated by Django 4.1.7 on 2023-05-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0027_product_vaiable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vaiable',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merchandise_web.product'),
        ),
    ]
