# Generated by Django 4.1.7 on 2023-05-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0029_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
