# Generated by Django 4.1.7 on 2023-05-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0031_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variant',
            new_name='size',
        ),
    ]
