# Generated by Django 4.1.7 on 2023-05-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0032_rename_variant_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
