# Generated by Django 4.1.7 on 2023-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0033_remove_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variantble',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
