# Generated by Django 4.1.7 on 2023-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0034_product_variantble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variantble',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
