# Generated by Django 4.1.7 on 2023-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0035_alter_product_variantble'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesign',
            name='design_option',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
