# Generated by Django 4.1.7 on 2023-05-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0036_userdesign_design_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('9oz', 'Small size with a capacity of 9 ounces')], max_length=5),
        ),
    ]
