# Generated by Django 4.1.7 on 2023-05-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0037_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('9oz', 'Small size with a capacity of 9 ounces'), ('16oz', 'Medium size with a capacity of 16 ounces'), ('25oz', 'Medium size with a capacity of 25 ounces'), ('32oz', 'Medium size with a capacity of 32 ounces'), ('60oz', 'Large size with a capacity of 60 ounces')], max_length=5),
        ),
    ]
