# Generated by Django 4.2 on 2023-06-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_web', '0038_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
